### ISSUE TITLE
I can't successfully use desktop version of corehunter3

### ISSUE THREAD

**Issue by hungweichen0327** [corehunter/corehunter3#107]
Dear community,

I can't successfully use desktop version of corehunter3. 

It said "An error has occurred" after I click the application of corehunter3.

Below is the log file: 1574675381150.log

[1574675381150.log](https://github.com/corehunter/corehunter3/files/3885960/1574675381150.log)

Thank you.

**Comment by daveneti** [comment]
Hi,

Thanks for the reporting the issue and the log file. I looks like a Java version compatibility issue. I will test on java 12 and see if I can repeat the issue.

**Comment by hungweichen0327** [comment]
Thank you for the help. I am looking forward to your test. :)

**Comment by daveneti** [comment]
I was able to reproduce the bug by installing java v13. 

`org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
        at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:386)
        at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:294)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultHeadlessContext(E4Application.java:490)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultContext(E4Application.java:504)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:203)
        at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:148)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
        at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:151)
        at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:375)
        ... 18 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct cannot be found by org.eclipse.e4.core.di_1.6.1.v20160712-0927
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:410)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 20 more

!ENTRY org.eclipse.e4.ui.workbench 4 0 2019-12-03 18:37:43.238
!MESSAGE FrameworkEvent ERROR
`

**Comment by daveneti** [comment]
It will take me a few days to update, because I have not worked on the UI for sometime. In the short term you can use java version 8 for the UI or the R version.

**Comment by hungweichen0327** [comment]
Thank you for the help. I got it!
